version: 2
jobs:
  build_frontend:
    docker:
      - image: circleci/node:8.10-stretch-browsers
    working_directory: ~/komiser
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{checksum "public/package.json"}}
      - run:
          name: Install dependencies
          command: cd public && npm install
      - save_cache:
          key: node-modules-{{checksum "public/package.json"}}
          paths:
            - public/node_modules
      - run:
          name: Build artifact
          command: cd public && npm run build
      - persist_to_workspace:
          root: public
          paths:
            - dist
  build_cli:
    docker:
      - image: golang:1.8
    working_directory: /go/src/github.com/mlabouardy/komiser
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/public
      - run:
          name: Install dependencies
          command: go get -v
      - run:
          name: Install go-bin-data
          command: |
           go get github.com/jteeuwen/go-bindata/...
           go get github.com/elazarl/go-bindata-assetfs/...
      - run:
         name: Fix path
         command: mv /tmp/public/dist .
      - run:
         name: Create assets
         command: go-bindata-assetfs -o template.go dist/ dist/assets/images/
      - run:
         name: Install gox
         command: go get github.com/mitchellh/gox
      - run:
         name: Build binary
         command: gox -osarch="linux/amd64"
      - run:
         name: Install AWS CLI
         command: |
          apt-get update
          apt-get install -y awscli

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build_frontend
            - build_cli:
                requires:
                    - build_frontend