version: 2
jobs:
  build_frontend:
    docker:
      - image: circleci/node:8.10-stretch-browsers
    working_directory: ~/komiser
    steps:
      - checkout
      - restore_cache:
          key: node-modules-{{checksum "public/package.json"}}
      - run:
          name: Install dependencies
          command: cd public && npm install
      - save_cache:
          key: node-modules-{{checksum "public/package.json"}}
          paths:
            - public/node_modules
      - run:
          name: Build artifact
          command: cd public && npm run build
      - persist_to_workspace:
          root: public
          paths:
            - dist
  build_cli:
    docker:
      - image: golang:1.8
    working_directory: /go/src/github.com/mlabouardy/komiser
    steps:
      - checkout
      - attach_workspace:
          at: /tmp/public
      - run:
          name: Install dependencies
          command: go get -v
      - run:
          name: Install go-bin-data
          command: |
           go get github.com/jteeuwen/go-bindata/...
           go get github.com/elazarl/go-bindata-assetfs/...
      - run:
         name: Fix path
         command: mv /tmp/public/dist .
      - run:
         name: Create assets
         command: go-bindata-assetfs -o template.go dist/ dist/assets/images/
      - run:
         name: Install gox
         command: go get github.com/mitchellh/gox
      - run:
         name: Build binary
         command: gox -osarch="linux/amd64 windows/amd64 darwin/amd64"
      - run:
         name: Install AWS CLI
         command: |
          apt-get update
          apt-get install -y awscli
          chmod +x komiser_windows_amd64.exe komiser_darwin_amd64 komiser_linux_amd64
      - run:
          name: Push Linux binary
          command: aws s3 cp komiser_linux_amd64 s3://komiser/1.0.0/linux/komiser --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - run:
          name: Push Windows binary
          command: aws s3 cp komiser_windows_amd64.exe s3://komiser/1.0.0/windows/komiser --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers
      - run:
          name: Push Mac OS X binary
          command: aws s3 cp komiser_darwin_amd64 s3://komiser/1.0.0/osx/komiser --grants read=uri=http://acs.amazonaws.com/groups/global/AllUsers

  build_docker:
    docker:
       - image: docker:18.02.0-ce
    steps:
        - checkout
        - setup_remote_docker
        - run:
            name: Build Komiser Docker Image
            command: docker build -t mlabouardy/komiser .
        - deploy:
            name: Push Komiser to DockerHub
            command: |
              docker login -u$DOCKERHUB_LOGIN -p$DOCKERHUB_PASSWORD
              docker tag mlabouardy/komiser mlabouardy/komiser:1.0.0
              docker push mlabouardy/komiser:1.0.0
      

workflows:
    version: 2
    build_and_deploy:
        jobs:
            - build_frontend
            - build_cli:
                requires:
                    - build_frontend
            - build_docker:
                requires:
                    - build_cli